# Generated by Django 4.1.1 on 2022-09-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared_document_store.base')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(default=None, max_length=700)),
            ],
            bases=('shared_document_store.base',),
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared_document_store.base')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            bases=('shared_document_store.base',),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared_document_store.base')),
                ('name', models.CharField(max_length=50)),
                ('folder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='folder_documents', to='shared_document_store.folders')),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='topic_documents', to='shared_document_store.topics')),
            ],
            bases=('shared_document_store.base',),
        ),
    ]
