# Generated by Django 4.1.1 on 2022-09-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_document_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='folder_id',
            new_name='folders',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='topic_id',
            new_name='topics',
        ),
    ]
