# Generated by Django 4.1.1 on 2022-09-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_document_store', '0002_rename_folder_id_document_folders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='shared_document_store.folder'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='shared_document_store.topic'),
        ),
    ]
