# Generated by Django 4.1.1 on 2022-09-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_document_store', '0004_alter_document_folders_alter_document_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='shared_document_store.folder'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='shared_document_store.topic'),
        ),
    ]
